clc;
clear all;
close all;
In_img=imread('fimg14.png');
figure(1);
imshow(In_img);
title("Original image");
gray_img=rgb2gray(In_img);
figure(2);
imshow(gray_img);
title("Grayscale image");
adj_img=imadjust(gray_img,[0.5 0.9],[]) ;
figure(3);
imshow(adj_img);
title("Adjusted image");
lvl=graythresh(adj_img);
bin_img=imbinarize(adj_img,lvl);
figure(4);
imshow(bin_img);
title("image after thresholding");
%rev_img=1-bin_img;
%imshow(rev_img);
%med_img=medfilt2(rev_img);
med_img=medfilt2(bin_img);
figure(5);
imshow(med_img);
title("Filtered image");
se=strel('disk',4);
cls_img=imclose(med_img,se);
figure(6);
imshow(cls_img);
title("closed image");
rmv_img=bwareaopen(cls_img,6000);
figure(7);
imshow(rmv_img);
title("image after bwareaopen");
i=im2single(In_img);
j=im2single(rmv_img);
out_img=i+j;
figure(8);
imshow(out_img);
title("Final Image");